### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by xinchundong** [bradyz/cross_view_transformers#5]
Hi, 
Thanks for your great work and sharing the code! I didn't find the codes for evaluation, will you release it sooner? Thanks!

**Comment by babyporgrammer** [comment]
thanks for the code, when will we have the eval code?

**Comment by sparkingcoding** [comment]
Since the nuScenes segmentation is performed on the validation set, I saw a lot of repos that don't have evaluation codes and just use the validation evaluation curve result during training. I tried to train the CVT model, and after it was finished, I checked the wanddb board and found the best result on validation@iou0.5 curve is around 36.0. I guess this is how it estimates the result,

**Comment by xiaoyucheri** [comment]
@sparkingcoding makes sense, thanks
