### ISSUE TITLE
camera internal and external parameters

### ISSUE THREAD

**Issue by duohaoxue** [bradyz/cross_view_transformers#7]
Hello, model training must be heavily dependent on camera extrinsic and extrinsic parameters? Will the effect be much worse if I use it?

      I_inv = batch['intrinsics'].inverse()           # b n 3 3
      E_inv = batch['extrinsics'].inverse()           # b n 4 4

Thanks a lot!

**Comment by bradyz** [comment]
If you don't have these camera parameters the model's performance would indeed decrease -
Table 3 shows the model's performance decreases by several points with unknown extrinsics.

If your camera pose is guaranteed fixed with respect to the ego vehicle, the network _could_ learn these parameters though and still perform well

**Comment by duohaoxue** [comment]
Thank you very much for your answers
